# Site settings
title: KRINGLES.ORG
email: peter@kringles.org
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal website, kringles.org.  Here I will have some
  simple information about myself and try to update on finds and things
  I have done.  Check back offen to see what I have been up too.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.kringles.org" # the base hostname & protocol for your site
github_username:  pkringle

# Build settings
markdown: kramdown
keep_files: ["CNAME", ".git", "README.md"]
